# Generated by Django 3.1.7 on 2021-03-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media_gallery',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
