# Generated by Django 3.1.7 on 2021-03-15 03:48

from django.db import migrations, models
import maaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0002_profile_media_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='media_gallery',
            field=models.ImageField(blank=True, null=True, upload_to=maaps.models.rename_file),
        ),
    ]
