# Generated by Django 3.1.7 on 2021-03-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0003_auto_20210315_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='media_gallery',
            new_name='profile_picture',
        ),
    ]
