# Generated by Django 3.1.7 on 2021-04-24 23:32

from django.db import migrations
import django_resized.forms
import maaps.models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0005_profile_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=90, size=[1920, 1280], upload_to=maaps.models.rename_file),
        ),
    ]
