# Generated by Django 3.1.7 on 2021-05-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0008_profile_commercial_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthly_payment',
            field=models.BooleanField(default=False),
        ),
    ]
