# Generated by Django 3.1.7 on 2021-05-09 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maaps', '0009_profile_monthly_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='include_tax',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SpaceRentPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SpaceRentPayments', to='maaps.invoice')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SpaceRentPayments', to='maaps.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spacerent_payments', to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
        ),
    ]
