# Generated by Django 3.1.7 on 2021-05-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0010_auto_20210509_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacerentpayment',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacerentpayment',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacerentpayment',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
