# Generated by Django 3.1.7 on 2021-05-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0012_auto_20210509_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postalcode',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
