# Generated by Django 3.1.7 on 2021-05-10 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0014_auto_20210510_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='currentSession',
            new_name='current_session',
        ),
    ]
