# Generated by Django 3.1.7 on 2021-05-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0016_auto_20210510_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinesessionpayment',
            old_name='totalpayment',
            new_name='value',
        ),
    ]
