# Generated by Django 3.1.7 on 2021-05-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0017_auto_20210510_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='current_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_session', to='maaps.machinesession'),
        ),
    ]
