# Generated by Django 3.1.7 on 2021-05-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0019_auto_20210513_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='total_payment',
            new_name='value',
        ),
    ]
