# Generated by Django 3.1.7 on 2021-05-14 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0021_auto_20210514_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceaccesstracking',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='spaceaccesstracking',
            name='transaction',
        ),
    ]
