# Generated by Django 3.1.7 on 2021-05-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0024_auto_20210515_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacerentpayment',
            name='type',
            field=models.CharField(blank=True, default='monthly', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
