# Generated by Django 3.1.7 on 2021-05-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0025_auto_20210515_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
