# Generated by Django 3.1.7 on 2021-05-18 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0027_spacerentpayment_for_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(blank=True, max_length=100)),
                ('discount', models.FloatField(default=0)),
                ('default', models.FloatField(default=0)),
                ('commercial', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='price_per_hour',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price_per_usage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='paying_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maaps.profile'),
        ),
    ]
