# Generated by Django 3.1.7 on 2021-05-18 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        Machine = apps.get_model('maaps', 'Machine')
        Machine.objects.update(price_per_hour=None)
        Machine.objects.update(price_per_usage=None)

    dependencies = [
        ('maaps', '0028_auto_20210518_0017'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='machine',
            name='price_per_hour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinePerHour', to='maaps.price'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price_per_usage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinePerUsage', to='maaps.price'),
        ),
    ]
