# Generated by Django 3.1.7 on 2021-05-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0031_profile_deposit_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='deposit_account',
            new_name='discount_account',
        ),
    ]
