# Generated by Django 3.1.7 on 2021-05-23 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0032_auto_20210518_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='price_per_hour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinePerHour', to='maaps.price'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='price_per_usage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machinePerUsage', to='maaps.price'),
        ),
    ]
