# Generated by Django 3.1.7 on 2021-07-13 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0034_prepaiddepositpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prepaiddepositpayment',
            old_name='value',
            new_name='price',
        ),
    ]
