# Generated by Django 3.1.7 on 2021-07-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0037_invoice_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='group_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
