# Generated by Django 3.1.7 on 2021-07-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0039_invoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='taxes',
            field=models.FloatField(default=0),
        ),
    ]
