# Generated by Django 4.2.2 on 2023-11-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maaps', '0041_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='members',
            field=models.FloatField(default=0),
        ),
    ]
